# This is a basic workflow to help you get started with Actions

name: Build T8

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ t8 ]
  pull_request:
    branches: [ t8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 1.8
          # The package type (jre, jdk, jdk+fx)
          java-package: jdk
          # The architecture (x86, x64) of the package.
          architecture: x64

      # Donwload openaf
      - name: Download openaf
        run : |
          cd $GITHUB_WORKSPACE && mkdir o && cd o && wget https://openaf.io/openaf.jar -O openaf.jar.orig && wget https://openaf.io/openaf.jar.repacked -O openaf.jar && java -jar openaf.jar --install
      # Runs a set of commands using the runners shell
      - name: Run OpenAF build
        run: |
          cd $GITHUB_WORKSPACE && ./o/ojob build.yaml
          
      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: openaf.jar.orig
          path: openaf.jar.orig
      
      - uses: actions/upload-artifact@v2
        with:
          name: openaf.jar
          path: openaf.jar
